
DROP TABLE "CACEIS_OWN"."CRE_4SIGHT_COATY";

 

CREATE TABLE "CACEIS_OWN"."CRE_4SIGHT_COATY" (

  "ID" NUMBER(20,0) NOT NULL,

  "FILENAME" VARCHAR2(500) NOT NULL,

  "LAUNCH_DATETIME" TIMESTAMP default sysdate NOT NULL,

  "LINENUMBER" NUMBER(20,0),

  "RAW_CRE" VARCHAR2(4000),

  "MQ_CRE" VARCHAR2(4000),

  "PROCESSED" NUMBER(1,0) DEFAULT 0 NOT NULL ,

  "COA" NUMBER(1,0) DEFAULT 0 NOT NULL ,

  "COD" NUMBER(1,0) DEFAULT 0 NOT NULL ,

  "UPDATE_DATETIME" TIMESTAMP default sysdate NOT NULL ,

  "ID_QUEUE_MESSAGE" VARCHAR2(500),

   PRIMARY KEY ("ID")

   );

GRANT ALL ON "CACEIS_OWN"."CRE_4SIGHT_COATY" TO "SECFIN_BAT";   

 

-- index

CREATE INDEX IDX_CRE_4SIGHT_COATY_FILENAME ON "CACEIS_OWN"."CRE_4SIGHT_COATY"(FILENAME); 

 

DROP   SEQUENCE  "CACEIS_OWN"."CRE_4SIGHT_COATY_SEQ";

CREATE SEQUENCE  "CACEIS_OWN"."CRE_4SIGHT_COATY_SEQ"  MINVALUE 1  INCREMENT BY 1 CACHE 20; 

GRANT ALL ON "CACEIS_OWN"."CRE_4SIGHT_COATY_SEQ" TO "SECFIN_BAT";
